services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: bfs-backend:latest
    container_name: bfs-backend
    restart: unless-stopped
    env_file:
      - ./.env
    # nginx (abstrafikskola-nginx) will proxy to http://bfs-backend:5000
    networks:
      - abs_app-network

networks:
  abs_app-network:
    external: true
